language: java
notifications:
 irc:
  channels:
   - "irc.esper.net#icbm"
  template:
   - "%{build_number} (%{branch} - %{commit}: %{commit_message} : %{author}): %{message} (%{build_url})"
install: true
script:
  - gradle build
jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk6
