language: java
before_install:
  - git submodule update --init --recursive
notifications:
 irc:
  channels:
   - "irc.esper.net#icbm"
  template:
   - "%{build_number} (%{branch} - %{commit}: %{commit_message} : %{author}): %{message} (%{build_url})"
install: true
script:
  - gradle build -PbambooshortPlanName=BBM-Dev -Pdmodcurse=61545 --refresh-dependencies
cache:
  directories:
    - $HOME/.gradle
    - .gradle
sudo: false
jdk:
  - oraclejdk7
  - openjdk6
