language: java
before_install:
  - git submodule update --init --recursive
  - chmod a+x gradlew
cache:
  directories:
    - $HOME/.gradle
    - .gradle
sudo: false
notifications:
  irc:
    channels:
      - "irc.esper.net#BBM-bots"
    skip_join: true
  template:
      - "%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message} "
      - "Change view : %{compare_url}"
      - "Build details : %{build_url} : duration : %{duration}"
install: true
script:
  - ./gradlew clean build coveralls jacocoTestReport -PbambooshortPlanName=BBM -Pdmodcurse=61545 -S -i --refresh-dependencies
jdk:
  - oraclejdk8
after_success:
  - bash <(curl -s https://codecov.io/bash)

